//
// gfx module - public interface
//
// - draws into a small band buffer, never a whole frame; a full 320x240 frame
//   is 150 KB and the chip has 128 KB of RAM, so the screen goes to the panel
//   a slice at a time
// - nothing in here touches hardware; a finished band leaves through a function
//   pointer, so this compiles and runs on the mac - that is how the layout gets
//   previewed before the panel works, and how test_gfx.c checks it
// - dirty regions: the screen says which rectangles changed, gfx repaints only
//   those, one band per call, and asks the screen to draw itself into each band;
//   every primitive clips itself to the band it is handed
// - pixels are RGB565 with the two bytes already swapped for the wire - the
//   ILI9341 wants the high byte first and the M4 stores the low byte first
//

#ifndef GFX_MODULE_H
#define GFX_MODULE_H

#include <stdbool.h>
#include <stdint.h>

#define GFX_W 320
#define GFX_H 240

// how many pixels one band holds - 320 x 16 rows, 10 KB. a narrow region gets
// more rows per band, a full-width one gets 16; either way one band is at most
// 2 ms on the wire at 42 MBit/s
#define GFX_BAND_PIXELS (GFX_W * 16)

typedef uint16_t gfx_color_t;   // RGB565, native order; swapped on the way into the band

#define GFX_RGB(r, g, b) \
    ((gfx_color_t)((((uint16_t)(r) & 0xF8u) << 8) | \
                   (((uint16_t)(g) & 0xFCu) << 3) | \
                   ((uint16_t)(b) >> 3)))

#define GFX_BLACK   GFX_RGB(0, 0, 0)
#define GFX_WHITE   GFX_RGB(255, 255, 255)
#define GFX_RED     GFX_RGB(255, 0, 0)
#define GFX_GREEN   GFX_RGB(0, 255, 0)
#define GFX_BLUE    GFX_RGB(0, 0, 255)

typedef struct {
    int16_t x, y, w, h;
} gfx_rect_t;

// one character: how wide its cell is, how far the cursor moves, and where
// its rows start in the font's bit table
typedef struct {
    uint8_t width;
    uint8_t advance;
    uint16_t offset;
} gfx_glyph_t;

typedef struct {
    uint8_t height;     // rows in every cell
    uint8_t ascent;     // rows above the baseline
    uint8_t first;      // character code of glyphs[0]
    uint8_t count;
    const gfx_glyph_t *glyphs;
    const uint8_t *bits;
} gfx_font_t;

// generated by tools/gen_fonts.py into App/Fonts/
extern const gfx_font_t font_small;    // labels and the GPS line
extern const gfx_font_t font_medium;   // values and the ring numbers
extern const gfx_font_t font_large;    // digits only, the centre number

typedef enum {
    GFX_ALIGN_LEFT = 0,
    GFX_ALIGN_CENTER,
    GFX_ALIGN_RIGHT,
} gfx_align_t;

// the screen draws itself into the band it is given, using the primitives
// below; called once per band, possibly many times per frame
typedef void (*gfx_paint_fn)(const gfx_rect_t *band);

// a finished band on its way to the panel; pixels are already in wire order
typedef void (*gfx_output_fn)(int16_t x, int16_t y, int16_t w, int16_t h,
                              const uint16_t *pixels);

void gfx_init(gfx_paint_fn paint, gfx_output_fn output);

// mark a rectangle as needing a repaint; overlapping marks merge
void gfx_invalidate(int16_t x, int16_t y, int16_t w, int16_t h);
void gfx_invalidate_all(void);

// true while something is still waiting to be repainted
bool gfx_dirty(void);

// paint and send one band of the oldest dirty rectangle; returns true if
// there is more to do - call it once per loop pass, never in a loop of its own
bool gfx_flush_band(void);

// bands sent since init, for the console
uint32_t gfx_bands_sent(void);

// ---- primitives, valid inside the paint callback only, clipped to the band ----

void gfx_fill_rect(int16_t x, int16_t y, int16_t w, int16_t h, gfx_color_t c);
void gfx_draw_rect(int16_t x, int16_t y, int16_t w, int16_t h, gfx_color_t c);  // 1 px outline
void gfx_hline(int16_t x, int16_t y, int16_t w, gfx_color_t c);
void gfx_vline(int16_t x, int16_t y, int16_t h, gfx_color_t c);
void gfx_fill_circle(int16_t cx, int16_t cy, int16_t r, gfx_color_t c);
// the area between two radii, r_inner < r_outer
void gfx_fill_ring(int16_t cx, int16_t cy, int16_t r_outer, int16_t r_inner, gfx_color_t c);

int16_t gfx_text_width(const gfx_font_t *font, const char *s);
// y is the top of the cell; x is the anchor the alignment works from
void gfx_draw_text(const gfx_font_t *font, int16_t x, int16_t y, gfx_align_t align,
                   const char *s, gfx_color_t c);

// native RGB565 <-> the byte order the panel wants
static inline uint16_t gfx_swap(gfx_color_t c) {
    return (uint16_t)((uint16_t)(c << 8) | (uint16_t)(c >> 8));
}

#endif // GFX_MODULE_H
