#!/usr/bin/env python3
#
# gen_fonts.py - turns a TTF into the bitmap font tables gfx.c draws with
#
# - run it from the repo root with the python.org 3.12 python, the one that
#   has matplotlib installed:
#     /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 tools/gen_fonts.py
# - matplotlib is only used for two things: its FreeType binding, which does the
#   rasterising, and the DejaVu Sans Bold it ships (Bitstream Vera licence, free
#   to embed); nothing else needs installing
# - output is App/Fonts/font_*.c, one table per size, checked in so the firmware
#   build never depends on this script
# - glyphs are 1-bit, rows packed MSB first, every glyph the same height (the
#   cell) with a shared baseline, so text lines up whatever it says
# - `--dump` prints a few glyphs as ASCII art to eyeball the placement
#

import os
import sys
import numpy as np
import matplotlib
from matplotlib.ft2font import FT2Font, FT2Image, LoadFlags

FONT_DIR = os.path.join(os.path.dirname(matplotlib.__file__), 'mpl-data', 'fonts', 'ttf')
FONT_PATH = os.path.join(FONT_DIR, 'DejaVuSans-Bold.ttf')
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'App', 'Fonts')

ASCII = ''.join(chr(c) for c in range(32, 127))

# name, em size in pixels, the characters it carries - the codes must be one
# unbroken run, gfx looks a glyph up as (code - first)
FONTS = [
    ('font_small', 11, ASCII),
    ('font_medium', 17, ASCII),
    ('font_large', 32, '-./0123456789'),   # contiguous codes 45..57
]

FLAGS = LoadFlags.RENDER | LoadFlags.TARGET_MONO


def metrics(face, ch):
    # FreeType hands back 26.6 fixed point: divide by 64 for pixels. the linear
    # advance is 16.16 and unrounded, which keeps proportional spacing honest
    g = face.load_char(ord(ch), flags=FLAGS)
    return {
        'bearing_x': int(round(g.horiBearingX / 64.0)),
        'bearing_y': int(round(g.horiBearingY / 64.0)),
        'ink_w': int(round(g.width / 64.0)),
        'ink_h': int(round(g.height / 64.0)),
        'advance': int(round(g.linearHoriAdvance / 65536.0)),
    }


def build(name, em_px, chars):
    for a, b in zip(chars, chars[1:]):
        assert ord(b) == ord(a) + 1, 'character set must be contiguous: %r' % chars
    # hinting_factor 1 keeps every horizontal metric in plain pixels; the
    # default of 8 stretches them for matplotlib's own subpixel layout
    face = FT2Font(FONT_PATH, hinting_factor=1)
    face.set_size(em_px, 72)   # at 72 dpi the point size is the pixel size

    ms = {ch: metrics(face, ch) for ch in chars}
    ascent = max(m['bearing_y'] for m in ms.values())
    descent = max(m['ink_h'] - m['bearing_y'] for m in ms.values())
    height = ascent + descent

    bits = bytearray()
    table = []
    for ch in chars:
        m = ms[ch]
        shift = -m['bearing_x'] if m['bearing_x'] < 0 else 0   # ink left of the origin
        width = max(m['advance'], m['bearing_x'] + m['ink_w']) + shift
        width = max(width, 1)
        advance = m['advance'] + shift

        canvas = FT2Image(width, height)
        if m['ink_w'] and m['ink_h']:
            g = face.load_char(ord(ch), flags=FLAGS)
            # the y handed to draw_glyph_to_bitmap is the top of the ink, so
            # the baseline sits bearing_y rows below it
            face.draw_glyph_to_bitmap(canvas, shift, ascent - m['bearing_y'], g, antialiased=False)
        cell = (np.asarray(canvas) > 0).astype(np.uint8)

        row_bytes = (width + 7) // 8
        offset = len(bits)
        for row in cell:
            bits.extend(np.packbits(row, bitorder='big').tobytes()[:row_bytes])
        table.append((ch, width, advance, offset, cell))

    return height, ascent, table, bits


def write_c(name, em_px, height, ascent, table, bits):
    first = ord(table[0][0])
    path = os.path.join(OUT_DIR, name + '.c')
    with open(path, 'w', newline='\n') as f:
        f.write('//\n')
        f.write('// %s - generated by tools/gen_fonts.py, do not edit by hand\n' % name)
        f.write('//\n')
        f.write('// - DejaVu Sans Bold at %d px em, %d glyphs from %s to %s\n'
                % (em_px, len(table), repr(table[0][0]), repr(table[-1][0])))
        f.write('// - every glyph is %d rows tall with the baseline %d rows down; rows are\n'
                % (height, ascent))
        f.write('//   packed MSB first, (width + 7) / 8 bytes per row\n')
        f.write('//\n\n')
        f.write('#include "gfx.h"\n\n')
        f.write('static const uint8_t %s_bits[] = {\n' % name)
        for i in range(0, len(bits), 16):
            f.write('    ' + ', '.join('0x%02X' % b for b in bits[i:i + 16]) + ',\n')
        f.write('};\n\n')
        f.write('// width, advance, offset into the bits\n')
        f.write('static const gfx_glyph_t %s_glyphs[] = {\n' % name)
        for ch, width, advance, offset, _ in table:
            label = 'space' if ch == ' ' else "'%s'" % ch
            f.write('    { %2d, %2d, %5d },  // %s\n' % (width, advance, offset, label))
        f.write('};\n\n')
        f.write('const gfx_font_t %s = {\n' % name)
        f.write('    .height = %d,\n' % height)
        f.write('    .ascent = %d,\n' % ascent)
        f.write('    .first = %d,\n' % first)
        f.write('    .count = %d,\n' % len(table))
        f.write('    .glyphs = %s_glyphs,\n' % name)
        f.write('    .bits = %s_bits,\n' % name)
        f.write('};\n')
    return path, len(bits) + 4 * len(table)


def dump(name, height, ascent, table, chars):
    print('%s: cell %d px, baseline after row %d' % (name, height, ascent - 1))
    for ch, width, advance, offset, cell in table:
        if ch in chars:
            print("'%s' width %d advance %d" % (ch, width, advance))
            for r, row in enumerate(cell):
                mark = '_' if r == ascent - 1 else ' '
                print(mark + ''.join('#' if v else '.' for v in row))


def main():
    want_dump = '--dump' in sys.argv
    for name, em_px, chars in FONTS:
        height, ascent, table, bits = build(name, em_px, chars)
        if want_dump:
            dump(name, height, ascent, table, 'Agj.' if name != 'font_large' else '8.')
        else:
            path, size = write_c(name, em_px, height, ascent, table, bits)
            print('%s: cell %d px, %d glyphs, %d bytes -> %s'
                  % (name, height, len(table), size, os.path.relpath(path)))


if __name__ == '__main__':
    main()
